;;;; tests/scaffold-test.lisp
;;;;
;;;; rove deftests for cl-harness/src/scaffold. All tests run against
;;;; uiop:with-temporary-directory tmpdirs and never touch the network
;;;; or an LLM provider.

(defpackage #:cl-harness/tests/scaffold-test
  (:use #:cl #:rove)
  (:import-from #:cl-harness/src/scaffold
                #:scaffold
                #:scaffold-result
                #:scaffold-result-status
                #:scaffold-result-paths-written
                #:scaffold-result-conflicts
                #:scaffold-bad-system-name
                #:scaffold-partial-state
                #:scaffold-partial-state-existing
                #:scaffold-partial-state-missing))

(in-package #:cl-harness/tests/scaffold-test)

(let ((%tmp-counter 0))
  (defun %tmp-dir ()
    "Return a fresh, unique temporary directory pathname for each call."
    (let ((d (merge-pathnames
              (format nil "cl-harness-scaffold-test-~A-~A/"
                      (get-internal-real-time)
                      (incf %tmp-counter))
              (uiop/stream:temporary-directory))))
      (ensure-directories-exist d)
      d)))

(deftest system-name-validation
  (testing "valid system names pass"
    (ok (cl-harness/src/scaffold::%validate-system-name "demo"))
    (ok (cl-harness/src/scaffold::%validate-system-name "foo-bar"))
    (ok (cl-harness/src/scaffold::%validate-system-name "a1")))
  (testing "invalid system names raise scaffold-bad-system-name"
    (dolist (bad '("Demo" "foo_bar" "" "0name" "-leading" "trailing-"))
      (ok (handler-case
              (progn (cl-harness/src/scaffold::%validate-system-name bad) nil)
            (scaffold-bad-system-name () t))
          (format nil "~S should be rejected" bad)))))

(deftest path-derivation
  (let ((root #P"/tmp/demo/"))
    (testing "asd path"
      (ok (equal #P"/tmp/demo/demo.asd"
                 (cl-harness/src/scaffold::%asd-path root "demo"))))
    (testing "src/main.lisp path"
      (ok (equal #P"/tmp/demo/src/main.lisp"
                 (cl-harness/src/scaffold::%src-main-path root))))
    (testing "tests/main-test.lisp default path"
      (ok (equal #P"/tmp/demo/tests/main-test.lisp"
                 (cl-harness/src/scaffold::%default-test-file-path root))))
    (testing ".gitignore path"
      (ok (equal #P"/tmp/demo/.gitignore"
                 (cl-harness/src/scaffold::%gitignore-path root))))
    (testing "default test-system from system"
      (ok (equal "demo/tests"
                 (cl-harness/src/scaffold::%default-test-system "demo"))))))

(deftest template-rendering
  (let ((asd (cl-harness/src/scaffold::%render-asd "demo" "demo/tests"))
        (src (cl-harness/src/scaffold::%render-src-main "demo"))
        (tst (cl-harness/src/scaffold::%render-tests-main "demo/tests"))
        (ign (cl-harness/src/scaffold::%render-gitignore)))
    (testing "asd template"
      (ok (search ":class :package-inferred-system" asd))
      (ok (search "(asdf:defsystem \"demo\"" asd))
      (ok (search "(asdf:defsystem \"demo/tests\"" asd))
      (ok (search "uiop:string-prefix-p \"demo/tests/\"" asd))
      (ok (search "uiop:symbol-call :rove :run" asd)))
    (testing "src/main.lisp template"
      (ok (search "(defpackage #:demo/src/main" src))
      (ok (search "(:nicknames #:demo)" src))
      (ok (search "(:use #:cl)" src))
      (ok (search "(:export)" src))
      (ok (search "(in-package #:demo/src/main)" src))
      (ok (search "Generated by cl-harness scaffold" src)))
    (testing "tests/main-test.lisp template"
      (ok (search "(defpackage #:demo/tests/main-test" tst))
      (ok (search "(:use #:cl #:rove)" tst))
      (ok (search "(in-package #:demo/tests/main-test)" tst)))
    (testing ".gitignore template"
      (ok (search "*.fasl" ign))
      (ok (search "*.fasl-tmp" ign))
      (ok (search ".cache/" ign)))))

(deftest detect-state
  (let* ((tmp (%tmp-dir))
         (asd  (cl-harness/src/scaffold::%asd-path tmp "demo"))
         (src  (cl-harness/src/scaffold::%src-main-path tmp))
         (test (cl-harness/src/scaffold::%default-test-file-path tmp)))
    (testing ":fresh when nothing exists"
      (multiple-value-bind (state existing missing)
          (cl-harness/src/scaffold::%detect-state tmp "demo" test)
        (ok (eq :fresh state))
        (ok (null existing))
        (ok (= 3 (length missing)))))
    (testing ":partial when some exist"
      (ensure-directories-exist asd)
      (with-open-file (s asd :direction :output) (write-string "dummy" s))
      (multiple-value-bind (state existing missing)
          (cl-harness/src/scaffold::%detect-state tmp "demo" test)
        (ok (eq :partial state))
        (ok (= 1 (length existing)))
        (ok (= 2 (length missing)))))
    (testing ":complete when all 3 exist"
      (ensure-directories-exist src)
      (ensure-directories-exist test)
      (with-open-file (s src :direction :output) (write-string "dummy" s))
      (with-open-file (s test :direction :output) (write-string "dummy" s))
      (multiple-value-bind (state existing missing)
          (cl-harness/src/scaffold::%detect-state tmp "demo" test)
        (ok (eq :complete state))
        (ok (= 3 (length existing)))
        (ok (null missing))))))

(defun %file-content (path)
  "Return the first line of PATH (used for one-line content checks)."
  (with-open-file (in path) (read-line in nil "")))

(defun %file-full-content (path)
  "Return the full content of PATH as one string."
  (with-output-to-string (out)
    (with-open-file (in path)
      (loop for line = (read-line in nil) while line
            do (write-line line out)))))

(deftest fresh-scaffold-writes-four-files
  (let ((tmp (%tmp-dir)))
    (let ((result (scaffold :project-root tmp :system "demo")))
      (testing "status is :written"
        (ok (eq :written (scaffold-result-status result))))
      (testing "4 files appear on disk"
        (ok (probe-file (merge-pathnames "demo.asd" tmp)))
        (ok (probe-file (merge-pathnames "src/main.lisp" tmp)))
        (ok (probe-file (merge-pathnames "tests/main-test.lisp" tmp)))
        (ok (probe-file (merge-pathnames ".gitignore" tmp))))
      (testing "paths-written lists 4 entries"
        (ok (= 4 (length (scaffold-result-paths-written result)))))
      (testing "conflicts is NIL on fresh"
        (ok (null (scaffold-result-conflicts result))))
      (testing "asd content references package-inferred-system"
        (let ((asd (%file-full-content (merge-pathnames "demo.asd" tmp))))
          (ok (search ":class :package-inferred-system" asd))))
      (testing "src defpackage has :nicknames #:demo"
        (let ((src (%file-full-content (merge-pathnames "src/main.lisp" tmp))))
          (ok (search "(:nicknames #:demo)" src)))))))

(deftest idempotent-on-already-scaffolded
  (let ((tmp (%tmp-dir)))
    (scaffold :project-root tmp :system "demo")
    (let ((mtime-before (file-write-date
                         (merge-pathnames "demo.asd" tmp)))
          (result (scaffold :project-root tmp :system "demo")))
      (testing "second invocation returns :already-present"
        (ok (eq :already-present (scaffold-result-status result))))
      (testing "paths-written is NIL on :already-present"
        (ok (null (scaffold-result-paths-written result))))
      (testing "file mtime unchanged"
        (ok (= mtime-before
               (file-write-date (merge-pathnames "demo.asd" tmp))))))))

(deftest refuses-partial-state
  (let ((tmp (%tmp-dir)))
    (let ((asd-path (merge-pathnames "demo.asd" tmp)))
      (ensure-directories-exist asd-path)
      (with-open-file (s asd-path :direction :output) (write-string "stub" s))
      (testing "scaffold-partial-state raised"
        (let ((raised
               (handler-case (progn (scaffold :project-root tmp :system "demo") nil)
                 (scaffold-partial-state (c) c))))
          (ok raised "condition was raised")
          (ok (= 1 (length (scaffold-partial-state-existing raised)))
              "1 existing file")
          (ok (= 2 (length (scaffold-partial-state-missing raised)))
              "2 missing files"))))))

(deftest force-overrides-partial-state
  (let ((tmp (%tmp-dir)))
    (let ((asd-path (merge-pathnames "demo.asd" tmp)))
      (ensure-directories-exist asd-path)
      (with-open-file (s asd-path :direction :output) (write-string "stub" s))
      (let ((result (scaffold :project-root tmp :system "demo" :force t)))
        (testing ":written status with force"
          (ok (eq :written (scaffold-result-status result))))
        (testing "asd content was overwritten"
          (let ((asd (%file-full-content asd-path)))
            (ok (search ":class :package-inferred-system" asd))
            (ok (not (search "stub" asd)))))))))
