;;;; tests/scaffold-test.lisp
;;;;
;;;; rove deftests for cl-harness/src/scaffold. All tests run against
;;;; uiop:with-temporary-directory tmpdirs and never touch the network
;;;; or an LLM provider.

(defpackage #:cl-harness/tests/scaffold-test
  (:use #:cl #:rove)
  (:import-from #:cl-harness/src/scaffold
                #:scaffold
                #:scaffold-result-status
                #:scaffold-result-paths-written
                #:scaffold-result-conflicts
                #:scaffold-bad-system-name
                #:scaffold-partial-state
                #:scaffold-partial-state-existing
                #:scaffold-partial-state-missing))

(in-package #:cl-harness/tests/scaffold-test)

(let ((%tmp-counter 0))
  (defun %tmp-dir ()
    "Return a fresh, unique temporary directory pathname for each call."
    (let ((d (merge-pathnames
              (format nil "cl-harness-scaffold-test-~A-~A/"
                      (get-internal-real-time)
                      (incf %tmp-counter))
              (uiop/stream:temporary-directory))))
      (ensure-directories-exist d)
      d)))

(deftest system-name-validation
  (testing "valid system names pass"
    (ok (cl-harness/src/scaffold::%validate-system-name "demo"))
    (ok (cl-harness/src/scaffold::%validate-system-name "foo-bar"))
    (ok (cl-harness/src/scaffold::%validate-system-name "a1")))
  (testing "invalid system names raise scaffold-bad-system-name"
    (dolist (bad '("Demo" "foo_bar" "" "0name" "-leading" "trailing-"))
      (ok (handler-case
              (progn (cl-harness/src/scaffold::%validate-system-name bad) nil)
            (scaffold-bad-system-name () t))
          (format nil "~S should be rejected" bad)))))

(deftest path-derivation
  (let ((root #P"/tmp/demo/"))
    (testing "asd path"
      (ok (equal #P"/tmp/demo/demo.asd"
                 (cl-harness/src/scaffold::%asd-path root "demo"))))
    (testing "src/main.lisp path"
      (ok (equal #P"/tmp/demo/src/main.lisp"
                 (cl-harness/src/scaffold::%src-main-path root))))
    (testing "tests/main-test.lisp default path"
      (ok (equal #P"/tmp/demo/tests/main-test.lisp"
                 (cl-harness/src/scaffold::%default-test-file-path root))))
    (testing ".gitignore path"
      (ok (equal #P"/tmp/demo/.gitignore"
                 (cl-harness/src/scaffold::%gitignore-path root))))
    (testing "default test-system from system"
      (ok (equal "demo/tests"
                 (cl-harness/src/scaffold::%default-test-system "demo"))))))

(deftest template-rendering
  (let ((asd (cl-harness/src/scaffold::%render-asd "demo" "demo/tests"))
        (src (cl-harness/src/scaffold::%render-src-main "demo"))
        (tst (cl-harness/src/scaffold::%render-tests-main "demo/tests"))
        (ign (cl-harness/src/scaffold::%render-gitignore)))
    (testing "asd template"
      (ok (search ":class :package-inferred-system" asd))
      (ok (search "(asdf:defsystem \"demo\"" asd))
      (ok (search "(asdf:defsystem \"demo/tests\"" asd))
      (ok (search "uiop:string-prefix-p \"demo/tests/\"" asd))
      (ok (search "uiop:symbol-call :rove :run" asd)))
    (testing "src/main.lisp template"
      (ok (search "(defpackage #:demo/src/main" src))
      (ok (search "(:nicknames #:demo)" src))
      (ok (search "(:use #:cl)" src))
      (ok (search "(:export)" src))
      (ok (search "(in-package #:demo/src/main)" src))
      (ok (search "Generated by cl-harness scaffold" src)))
    (testing "tests/main-test.lisp template"
      (ok (search "(defpackage #:demo/tests/main-test" tst))
      (ok (search "(:use #:cl #:rove)" tst))
      (ok (search "(in-package #:demo/tests/main-test)" tst)))
    (testing ".gitignore template"
      (ok (search "*.fasl" ign))
      (ok (search "*.fasl-tmp" ign))
      (ok (search ".cache/" ign)))))

(deftest detect-state
  (let* ((tmp (%tmp-dir))
         (asd  (cl-harness/src/scaffold::%asd-path tmp "demo"))
         (src  (cl-harness/src/scaffold::%src-main-path tmp))
         (test (cl-harness/src/scaffold::%default-test-file-path tmp)))
    (testing ":fresh when nothing exists"
      (multiple-value-bind (state existing missing)
          (cl-harness/src/scaffold::%detect-state tmp "demo" test)
        (ok (eq :fresh state))
        (ok (null existing))
        (ok (= 3 (length missing)))))
    (testing ":partial when some exist"
      (ensure-directories-exist asd)
      (with-open-file (s asd :direction :output) (write-string "dummy" s))
      (multiple-value-bind (state existing missing)
          (cl-harness/src/scaffold::%detect-state tmp "demo" test)
        (ok (eq :partial state))
        (ok (= 1 (length existing)))
        (ok (= 2 (length missing)))))
    (testing ":complete when all 3 exist"
      (ensure-directories-exist src)
      (ensure-directories-exist test)
      (with-open-file (s src :direction :output) (write-string "dummy" s))
      (with-open-file (s test :direction :output) (write-string "dummy" s))
      (multiple-value-bind (state existing missing)
          (cl-harness/src/scaffold::%detect-state tmp "demo" test)
        (ok (eq :complete state))
        (ok (= 3 (length existing)))
        (ok (null missing))))))

(defun %file-content (path)
  "Return the first line of PATH (used for one-line content checks)."
  (with-open-file (in path) (read-line in nil "")))

(defun %file-full-content (path)
  "Return the full content of PATH as one string."
  (with-output-to-string (out)
    (with-open-file (in path)
      (loop for line = (read-line in nil) while line
            do (write-line line out)))))

(deftest fresh-scaffold-writes-four-files
  (let ((tmp (%tmp-dir)))
    (let ((result (scaffold :project-root tmp :system "demo")))
      (testing "status is :written"
        (ok (eq :written (scaffold-result-status result))))
      (testing "4 files appear on disk"
        (ok (probe-file (merge-pathnames "demo.asd" tmp)))
        (ok (probe-file (merge-pathnames "src/main.lisp" tmp)))
        (ok (probe-file (merge-pathnames "tests/main-test.lisp" tmp)))
        (ok (probe-file (merge-pathnames ".gitignore" tmp))))
      (testing "paths-written lists 4 entries"
        (ok (= 4 (length (scaffold-result-paths-written result)))))
      (testing "conflicts is NIL on fresh"
        (ok (null (scaffold-result-conflicts result))))
      (testing "asd content references package-inferred-system"
        (let ((asd (%file-full-content (merge-pathnames "demo.asd" tmp))))
          (ok (search ":class :package-inferred-system" asd))))
      (testing "src defpackage has :nicknames #:demo"
        (let ((src (%file-full-content (merge-pathnames "src/main.lisp" tmp))))
          (ok (search "(:nicknames #:demo)" src)))))))

(deftest idempotent-on-already-scaffolded
  (let ((tmp (%tmp-dir)))
    (scaffold :project-root tmp :system "demo")
    (let ((mtime-before (file-write-date (merge-pathnames "demo.asd" tmp))))
      (let ((result (scaffold :project-root tmp :system "demo")))
        (testing "second invocation returns :already-present"
          (ok (eq :already-present (scaffold-result-status result))))
        (testing "paths-written is NIL on :already-present"
          (ok (null (scaffold-result-paths-written result))))
        (testing "file mtime unchanged"
          (ok (= mtime-before (file-write-date (merge-pathnames "demo.asd" tmp)))))))))

(deftest refuses-partial-state
  (let ((tmp (%tmp-dir)))
    (let ((asd-path (merge-pathnames "demo.asd" tmp)))
      (ensure-directories-exist asd-path)
      (with-open-file (s asd-path :direction :output) (write-string "stub" s))
      (testing "scaffold-partial-state raised"
        (let ((raised
               (handler-case (progn (scaffold :project-root tmp :system "demo") nil)
                 (scaffold-partial-state (c) c))))
          (ok raised "condition was raised")
          (ok (= 1 (length (scaffold-partial-state-existing raised)))
              "1 existing file")
          (ok (= 2 (length (scaffold-partial-state-missing raised)))
              "2 missing files"))))))

(deftest force-overrides-partial-state
  (let ((tmp (%tmp-dir)))
    (let ((asd-path (merge-pathnames "demo.asd" tmp)))
      (ensure-directories-exist asd-path)
      (with-open-file (s asd-path :direction :output) (write-string "stub" s))
      (let ((result (scaffold :project-root tmp :system "demo" :force t)))
        (testing ":written status with force"
          (ok (eq :written (scaffold-result-status result))))
        (testing "asd content was overwritten"
          (let ((asd (%file-full-content asd-path)))
            (ok (search ":class :package-inferred-system" asd))
            (ok (not (search "stub" asd)))))))))

(deftest creates-project-root-if-missing
  (let ((tmp (%tmp-dir)))
    (let* ((deep (merge-pathnames "deeply/nested/dir/" tmp))
           (result (scaffold :project-root deep :system "demo")))
      (testing ":written status"
        (ok (eq :written (scaffold-result-status result))))
      (testing "deep dir exists"
        (ok (uiop:directory-exists-p deep)))
      (testing "asd file at correct path"
        (ok (probe-file (merge-pathnames "demo.asd" deep)))))))

(deftest generated-asd-loads-via-asdf
  (let ((tmp (%tmp-dir)))
    (scaffold :project-root tmp :system "scaffolddemoasd")
    (unwind-protect
         (progn
           (testing "asdf:load-asd succeeds"
             (ok (handler-case
                     (progn
                       (asdf:load-asd
                        (merge-pathnames "scaffolddemoasd.asd" tmp))
                       t)
                   (error (c)
                     (format *error-output* "asd load failed: ~A~%" c)
                     nil))))
           (testing "main system is registered"
             (ok (asdf:find-system "scaffolddemoasd" nil)))
           (testing "test system is registered"
             (ok (asdf:find-system "scaffolddemoasd/tests" nil))))
      ;; cleanup: avoid asdf:*defined-systems* pollution
      (asdf:clear-system "scaffolddemoasd")
      (asdf:clear-system "scaffolddemoasd/tests"))))

(defun %read-all-forms (path)
  "Read every top-level form from PATH; return them as a list."
  (with-open-file (in path)
    (loop for form = (read in nil :eof)
          until (eq form :eof)
          collect form)))

(deftest generated-defpackage-forms-parse
  (let ((tmp (%tmp-dir)))
    (scaffold :project-root tmp :system "demo")
    (testing "src/main.lisp parses to 2 forms (defpackage + in-package)"
      (let ((forms (%read-all-forms (merge-pathnames "src/main.lisp" tmp))))
        (ok (= 2 (length forms)))
        (ok (eq 'defpackage (caar forms)))
        (ok (eq 'in-package (caadr forms)))))
    (testing "tests/main-test.lisp parses to 2 forms"
      (let ((forms (%read-all-forms
                    (merge-pathnames "tests/main-test.lisp" tmp))))
        (ok (= 2 (length forms)))
        (ok (eq 'defpackage (caar forms)))
        (ok (eq 'in-package (caadr forms)))))
    (testing "asd parses to 2 defsystem forms"
      (let ((forms (%read-all-forms (merge-pathnames "demo.asd" tmp))))
        (ok (= 2 (length forms)))
        (ok (equal '(asdf:defsystem "demo") (subseq (first forms) 0 2)))
        (ok (equal '(asdf:defsystem "demo/tests")
                   (subseq (second forms) 0 2)))))))

(deftest test-system-and-test-file-overrides
  (let ((tmp (%tmp-dir)))
    (let* ((custom-test-file (merge-pathnames "altdir/integration.lisp" tmp))
           (result (scaffold :project-root tmp
                             :system "demo"
                             :test-system "demo/integration"
                             :test-file custom-test-file)))
      (testing ":written status"
        (ok (eq :written (scaffold-result-status result))))
      (testing "custom test file used"
        (ok (probe-file custom-test-file))
        (ok (not (probe-file (merge-pathnames "tests/main-test.lisp" tmp)))))
      (testing "asd references custom test-system"
        (let ((asd (%file-full-content (merge-pathnames "demo.asd" tmp))))
          (ok (search "(asdf:defsystem \"demo/integration\"" asd))
          (ok (search "\"demo/integration/main-test\"" asd))))
      (testing "tests defpackage uses custom test-system"
        (let ((tst (%file-full-content custom-test-file)))
          (ok (search "(defpackage #:demo/integration/main-test" tst)))))))

(deftest facade-re-exports
  (testing "cl-harness:scaffold is exported"
    (ok (eq 'cl-harness/src/scaffold:scaffold
            (find-symbol "SCAFFOLD" :cl-harness))))
  (testing "cl-harness:scaffold-result-status is exported"
    (ok (eq 'cl-harness/src/scaffold:scaffold-result-status
            (find-symbol "SCAFFOLD-RESULT-STATUS" :cl-harness))))
  (testing "cl-harness:scaffold-bad-system-name is exported"
    (ok (eq 'cl-harness/src/scaffold:scaffold-bad-system-name
            (find-symbol "SCAFFOLD-BAD-SYSTEM-NAME" :cl-harness)))))
