;;;; src/main.lisp
;;;;
;;;; Top-level facade for cl-harness. Re-exports the user-facing API surface
;;;; (config + log + cli) so callers can `(:use :cl-harness)' without knowing
;;;; the internal package-inferred-system layout. Re-exports work via
;;;; :import-from + :export, which share symbol identity with the source
;;;; packages — no fdefinition shimming required.

(defpackage #:cl-harness/src/main
  (:nicknames #:cl-harness)
  (:use #:cl)
  (:import-from #:cl-harness/src/config
                #:run-config
                #:make-run-config)
  (:import-from #:cl-harness/src/log
                #:run-logger
                #:open-run-logger
                #:close-run-logger
                #:log-event
                #:with-run-logger)
  (:import-from #:cl-harness/src/cli
                #:fix
                #:bench
                #:develop
                #:format-develop-report
                #:format-develop-report-markdown
                #:format-develop-report-structured)
  (:import-from #:cl-harness/src/abstraction
                #:abstraction-decision
                #:abstraction-decision-kind
                #:abstraction-decision-name
                #:abstraction-decision-rationale
                #:abstraction-decision-step-index
                #:make-abstraction-decision
                #:parse-abstraction-decisions
                #:format-abstraction-ledger-markdown)
  (:import-from #:cl-harness/src/integration
                #:package-info
                #:package-info-name
                #:package-info-nicknames
                #:package-info-exports
                #:package-info-imports
                #:package-info-uses
                #:package-info-file
                #:integration-issue
                #:integration-issue-kind
                #:integration-issue-file
                #:integration-issue-package
                #:integration-issue-description
                #:gather-package-graph
                #:find-integration-issues
                #:format-integration-issues-markdown)
  (:import-from #:cl-harness/src/cli-main
                #:main)
  (:import-from #:cl-harness/src/mcp
                #:mcp-client
                #:make-mcp-client
                #:mcp-client-url
                #:mcp-client-session-id
                #:mcp-error
                #:initialize-mcp
                #:list-tools
                #:call-tool
                #:close-mcp-client)
  (:import-from #:cl-harness/src/mcp-stdio
                #:make-stdio-mcp-client
                #:make-stdio-mcp-transport
                #:stdio-mcp-transport
                #:stdio-mcp-error)
  (:import-from #:cl-harness/src/model
                #:openai-compatible-provider
                #:make-openai-provider
                #:provider-default-reasoning-effort
                #:provider-default-extra-body
                #:make-chat-message
                #:chat-response
                #:chat-response-content
                #:chat-response-total-tokens
                #:complete-chat
                #:model-error)
  (:import-from #:cl-harness/src/action
                #:agent-action
                #:agent-action-type
                #:parse-action
                #:action-parse-error)
  (:import-from #:cl-harness/src/policy
                #:tool-policy
                #:make-tool-policy
                #:policy-mode
                #:allowed-tool-p)
  (:import-from #:cl-harness/src/verify
                #:verify-result
                #:verify-result-status
                #:verify-result-success-p
                #:verify-task
                #:clean-verify-task)
  (:import-from #:cl-harness/src/agent
                #:agent-state
                #:agent-state-status
                #:agent-state-turn
                #:agent-state-final-verify
                #:agent-state-patch-count
                #:agent-state-patch-attempts
                #:agent-state-token-total
                #:agent-state-tool-call-count
                #:agent-state-read-file-count
                #:agent-state-repl-eval-count
                #:agent-state-limit-hit
                #:agent-state-reason
                #:run-agent
                #:format-final-report)
  (:import-from #:cl-harness/src/planner
                #:plan-step
                #:plan-step-index
                #:plan-step-issue
                #:plan-step-test-name
                #:plan-step-test-source
                #:plan-step-files-to-modify
                ;; v0.4 Phase 1:
                #:plan-step-purpose
                #:plan-step-acceptance-criteria
                #:plan-step-investigation-targets
                #:plan-step-risks
                #:plan-step-needs-exploration
                #:plan-step-adopted-abstractions
                #:plan-step-rejected-abstractions
                #:investigation-target
                #:investigation-target-kind
                #:investigation-target-name
                #:investigation-target-intent
                #:plan-development
                #:planner-error
                #:+supported-development-modes+)
  (:import-from #:cl-harness/src/orchestrator
                #:develop-step-result
                #:develop-step-result-status
                #:develop-step-result-step-index
                #:develop-step-result-test-name
                #:develop-step-result-run-config
                #:develop-step-result-run-agent-state
                #:develop-step-result-explore-result
                #:develop-step-result-abstraction-decisions
                #:develop-result
                #:develop-result-status
                #:develop-result-develop-state
                #:develop-result-final-plan
                #:develop-result-step-results
                #:develop-result-replan-count
                #:develop-result-limit-hit
                #:develop-result-abstraction-ledger
                #:develop-result-integration-issues
                #:develop-result-reason
                #:execute-plan)
  (:import-from #:cl-harness/src/explore
                #:explore-result
                #:explore-result-status
                #:explore-result-memo
                #:explore-result-turns
                #:explore-result-token-total
                #:run-explore-agent)
  (:import-from #:cl-harness/src/compact
                #:approximate-history-tokens
                #:compact-history)
  (:import-from #:cl-harness/src/inventory
                #:gather-project-inventory)
  (:import-from #:cl-harness/src/develop-bench
                #:develop-task
                #:develop-task-id
                #:develop-task-goal
                #:develop-task-system
                #:develop-task-test-system
                #:develop-task-test-file
                #:develop-task-path
                #:develop-task-fixture-path
                #:develop-task-error
                #:develop-task-error-message
                #:load-develop-task
                #:discover-develop-tasks
                #:prepare-develop-task-sandbox)
  (:import-from #:cl-harness/src/bench
                #:bench-task
                #:bench-task-id
                #:bench-result
                #:bench-result-status
                #:bench-result-success-p
                #:bench-result-limit-hit
                #:bench-result-tool-call-count
                #:bench-result-read-file-count
                #:bench-result-repl-eval-count
                #:load-bench-task
                #:discover-tasks
                #:run-benchmark-task
                #:run-benchmark-task-trials
                #:run-benchmark-suite
                #:aggregate-results
                #:format-suite-report
                #:format-suite-report-markdown)
  (:export #:fix
           #:bench
           #:develop
           #:format-develop-report
           #:format-develop-report-markdown
           #:format-develop-report-structured
           #:abstraction-decision
           #:abstraction-decision-kind
           #:abstraction-decision-name
           #:abstraction-decision-rationale
           #:abstraction-decision-step-index
           #:make-abstraction-decision
           #:parse-abstraction-decisions
           #:format-abstraction-ledger-markdown
           #:main
           #:run-config
           #:make-run-config
           #:run-logger
           #:open-run-logger
           #:close-run-logger
           #:log-event
           #:with-run-logger
           #:mcp-client
           #:make-mcp-client
           #:mcp-client-url
           #:mcp-client-session-id
           #:mcp-error
           #:initialize-mcp
           #:list-tools
           #:call-tool
           #:close-mcp-client
           #:make-stdio-mcp-client
           #:make-stdio-mcp-transport
           #:stdio-mcp-transport
           #:stdio-mcp-error
           #:openai-compatible-provider
           #:make-openai-provider
           #:provider-default-reasoning-effort
           #:provider-default-extra-body
           #:make-chat-message
           #:chat-response
           #:chat-response-content
           #:chat-response-total-tokens
           #:complete-chat
           #:model-error
           #:agent-action
           #:agent-action-type
           #:parse-action
           #:action-parse-error
           #:tool-policy
           #:make-tool-policy
           #:policy-mode
           #:allowed-tool-p
           #:verify-result
           #:verify-result-status
           #:verify-result-success-p
           #:verify-task
           #:clean-verify-task
           #:agent-state
           #:agent-state-status
           #:agent-state-turn
           #:agent-state-final-verify
           #:agent-state-patch-count
           #:agent-state-patch-attempts
           #:agent-state-token-total
           #:agent-state-tool-call-count
           #:agent-state-read-file-count
           #:agent-state-repl-eval-count
           #:agent-state-limit-hit
           #:agent-state-reason
           #:run-agent
           #:format-final-report
           #:plan-step
           #:plan-step-index
           #:plan-step-issue
           #:plan-step-test-name
           #:plan-step-test-source
           #:plan-step-files-to-modify
           #:plan-step-purpose
           #:plan-step-acceptance-criteria
           #:plan-step-investigation-targets
           #:plan-step-risks
           #:plan-step-needs-exploration
           #:plan-step-adopted-abstractions
           #:plan-step-rejected-abstractions
           #:investigation-target
           #:investigation-target-kind
           #:investigation-target-name
           #:investigation-target-intent
           #:plan-development
           #:planner-error
           #:+supported-development-modes+
           #:develop-step-result
           #:develop-step-result-status
           #:develop-step-result-step-index
           #:develop-step-result-test-name
           #:develop-step-result-run-config
           #:develop-step-result-run-agent-state
           #:develop-step-result-explore-result
           #:develop-step-result-abstraction-decisions
           #:develop-result
           #:develop-result-status
           #:develop-result-develop-state
           #:develop-result-final-plan
           #:develop-result-step-results
           #:develop-result-replan-count
           #:develop-result-limit-hit
           #:develop-result-abstraction-ledger
           #:develop-result-integration-issues
           #:develop-result-reason
           #:execute-plan
           #:package-info
           #:package-info-name
           #:package-info-nicknames
           #:package-info-exports
           #:package-info-imports
           #:package-info-uses
           #:package-info-file
           #:integration-issue
           #:integration-issue-kind
           #:integration-issue-file
           #:integration-issue-package
           #:integration-issue-description
           #:gather-package-graph
           #:find-integration-issues
           #:format-integration-issues-markdown
           #:explore-result
           #:explore-result-status
           #:explore-result-memo
           #:explore-result-turns
           #:explore-result-token-total
           #:run-explore-agent
           #:approximate-history-tokens
           #:compact-history
           #:gather-project-inventory
           #:develop-task
           #:develop-task-id
           #:develop-task-goal
           #:develop-task-system
           #:develop-task-test-system
           #:develop-task-test-file
           #:develop-task-path
           #:develop-task-fixture-path
           #:develop-task-error
           #:develop-task-error-message
           #:load-develop-task
           #:discover-develop-tasks
           #:prepare-develop-task-sandbox
           #:bench-task
           #:bench-task-id
           #:bench-result
           #:bench-result-status
           #:bench-result-success-p
           #:bench-result-limit-hit
           #:bench-result-tool-call-count
           #:bench-result-read-file-count
           #:bench-result-repl-eval-count
           #:load-bench-task
           #:discover-tasks
           #:run-benchmark-task
           #:run-benchmark-task-trials
           #:run-benchmark-suite
           #:aggregate-results
           #:format-suite-report
           #:format-suite-report-markdown))

(in-package #:cl-harness/src/main)
