;;;; src/scaffold.lisp
;;;;
;;;; LLM-free, deterministic ASDF + rove scaffold generator.
;;;; Spec: docs/superpowers/specs/2026-05-22-scaffold-command-design.md

(defpackage #:cl-harness/src/scaffold
  (:use #:cl)
  (:export #:scaffold
           #:scaffold-result
           #:scaffold-result-status
           #:scaffold-result-paths-written
           #:scaffold-result-conflicts
           #:scaffold-error
           #:scaffold-error-message
           #:scaffold-bad-system-name
           #:scaffold-bad-system-name-name
           #:scaffold-partial-state
           #:scaffold-partial-state-existing
           #:scaffold-partial-state-missing))

(in-package #:cl-harness/src/scaffold)

(define-condition scaffold-error (error)
  ((message :initarg :message :reader scaffold-error-message))
  (:report (lambda (c s) (write-string (scaffold-error-message c) s))))

(define-condition scaffold-bad-system-name (scaffold-error)
  ((name :initarg :name :reader scaffold-bad-system-name-name)))

(define-condition scaffold-partial-state (scaffold-error)
  ((existing :initarg :existing :reader scaffold-partial-state-existing)
   (missing  :initarg :missing  :reader scaffold-partial-state-missing)))

(defun %valid-system-name-char-p (c first-p)
  (or (and first-p (char<= #\a c #\z))
      (and (not first-p)
           (or (char<= #\a c #\z)
               (char<= #\0 c #\9)
               (char= c #\-)))))

(defun %validate-system-name (name)
  "Return T if NAME matches ^[a-z][a-z0-9-]*$ and does not end with -.
Raise SCAFFOLD-BAD-SYSTEM-NAME otherwise."
  (let ((reject (lambda ()
                  (error 'scaffold-bad-system-name
                         :name name
                         :message
                         (format nil
                                 "invalid system name ~S — must match ~
^[a-z][a-z0-9-]*$ and not end with '-'"
                                 name)))))
    (unless (and (stringp name) (plusp (length name)))
      (funcall reject))
    (loop for i from 0 below (length name)
          for ch = (char name i)
          unless (%valid-system-name-char-p ch (zerop i))
          do (funcall reject))
    (when (char= (char name (1- (length name))) #\-)
      (funcall reject))
    t))

(defun %ensure-pathname (root)
  "Coerce ROOT to a directory pathname (trailing slash enforced)."
  (uiop:ensure-directory-pathname root))

(defun %asd-path (root system)
  "Return the pathname for ROOT/SYSTEM.asd."
  (merge-pathnames (format nil "~A.asd" system) (%ensure-pathname root)))

(defun %src-main-path (root)
  "Return the pathname for ROOT/src/main.lisp."
  (merge-pathnames "src/main.lisp" (%ensure-pathname root)))

(defun %default-test-file-path (root)
  "Return the pathname for ROOT/tests/main-test.lisp."
  (merge-pathnames "tests/main-test.lisp" (%ensure-pathname root)))

(defun %gitignore-path (root)
  "Return the pathname for ROOT/.gitignore."
  (merge-pathnames ".gitignore" (%ensure-pathname root)))

(defun %default-test-system (system)
  "Return the conventional test system name for SYSTEM (i.e., SYSTEM/tests)."
  (format nil "~A/tests" system))

(defun %render-asd (system test-system)
  "Return a string containing the .asd file content for SYSTEM and TEST-SYSTEM."
  (format nil "~
(asdf:defsystem \"~A\"
  :class :package-inferred-system
  :description \"TODO: short description\"
  :license \"MIT\"
  :version \"0.0.1\"
  :depends-on (\"~A/src/main\")
  :in-order-to ((test-op (test-op \"~A\"))))

(asdf:defsystem \"~A\"
  :class :package-inferred-system
  :depends-on (\"rove\"
               \"~A\"
               \"~A/main-test\")
  :perform (test-op (o c)
                    (declare (ignore o))
                    (let ((test-packages
                           (remove-if-not
                            (lambda (dep)
                              (and (stringp dep)
                                   (uiop:string-prefix-p \"~A/\" dep)))
                            (asdf:system-depends-on c))))
                      (uiop:symbol-call :rove :run test-packages))))
"
          system system test-system
          test-system
          system test-system
          test-system))

(defun %render-src-main (system)
  "Return a string containing the src/main.lisp file content for SYSTEM."
  (format nil "~
;;;; src/main.lisp
;;;;
;;;; Generated by cl-harness scaffold.

(defpackage #:~A/src/main
  (:nicknames #:~A)
  (:use #:cl)
  (:export))

(in-package #:~A/src/main)
"
          system system system))

(defun %render-tests-main (test-system)
  "Return a string containing the tests/main-test.lisp file content for TEST-SYSTEM."
  (format nil "~
;;;; tests/main-test.lisp
;;;;
;;;; Generated by cl-harness scaffold.

(defpackage #:~A/main-test
  (:use #:cl #:rove))

(in-package #:~A/main-test)
"
          test-system test-system))

(defun %render-gitignore ()
  "Return a string containing a default .gitignore for Common Lisp projects."
  "*.fasl
*.fasl-tmp
.cache/
")

(defun %detect-state (project-root system test-file-path)
  "Return (values STATE EXISTING MISSING).
STATE is one of :fresh / :partial / :complete.
EXISTING and MISSING are lists of pathnames (subsets of the 3
scaffold-tracked files). The .gitignore file is NOT tracked."
  (let* ((tracked (list (%asd-path project-root system)
                        (%src-main-path project-root)
                        test-file-path))
         (existing (remove-if-not #'probe-file tracked))
         (missing  (remove-if     #'probe-file tracked))
         (state (cond ((null existing) :fresh)
                      ((null missing)  :complete)
                      (t               :partial))))
    (values state existing missing)))

(defclass scaffold-result ()
  ((status :initarg :status :reader scaffold-result-status)
   (paths-written :initarg :paths-written :initform nil
                  :reader scaffold-result-paths-written)
   (conflicts :initarg :conflicts :initform nil
              :reader scaffold-result-conflicts))
  (:documentation
   "Return value of SCAFFOLD. STATUS is one of :WRITTEN, :ALREADY-PRESENT,
or :REFUSED. PATHS-WRITTEN is the list of files actually written; NIL
for :ALREADY-PRESENT and :REFUSED. CONFLICTS is the list of pre-existing
files that triggered a :REFUSED; NIL otherwise."))

(defun %write-file (path content)
  "Write CONTENT string to PATH, creating directories as needed.
Uses :if-exists :supersede so re-running scaffold overwrites safely.
Returns PATH."
  (ensure-directories-exist path)
  (with-open-file (out path :direction :output
                            :if-exists :supersede
                            :if-does-not-exist :create)
    (write-string content out))
  path)

(defun %write-all-scaffold-files (project-root system test-system test-file-path)
  "Write the four scaffold files and return their pathnames as a list.
Order: asd, src/main.lisp, tests/main-test.lisp, .gitignore."
  (let ((asd-path  (%asd-path project-root system))
        (src-path  (%src-main-path project-root))
        (gitignore (%gitignore-path project-root)))
    (list (%write-file asd-path  (%render-asd system test-system))
          (%write-file src-path  (%render-src-main system))
          (%write-file test-file-path (%render-tests-main test-system))
          (%write-file gitignore (%render-gitignore)))))

(defun scaffold (&key project-root system test-system test-file force)
  "Emit a 4-file ASDF + rove project skeleton under PROJECT-ROOT.

Required: PROJECT-ROOT (pathname designator) and SYSTEM (string).
Optional: TEST-SYSTEM (defaults to \"<system>/tests\"),
TEST-FILE (defaults to <project-root>/tests/main-test.lisp),
FORCE (override the partial-state refuse and overwrite all files).

Return a SCAFFOLD-RESULT. See spec
docs/superpowers/specs/2026-05-22-scaffold-command-design.md."
  (%validate-system-name system)
  (let* ((root (uiop:ensure-directory-pathname project-root))
         (ts   (or test-system (%default-test-system system)))
         (tf   (or (and test-file (pathname test-file))
                   (%default-test-file-path root))))
    (ensure-directories-exist root)
    (multiple-value-bind (state existing missing)
        (%detect-state root system tf)

      (cond
        ((eq state :complete)
         (make-instance 'scaffold-result :status :already-present))
        ((or (eq state :fresh) force)
         (make-instance 'scaffold-result
                        :status :written
                        :paths-written
                        (%write-all-scaffold-files root system ts tf)))
        (t
         (error 'scaffold-partial-state
                :existing existing
                :missing missing
                :message
                (format nil
                        "refusing to scaffold ~A: ~D file(s) already exist; ~
                             pass :FORCE T to overwrite"
                        root (length existing))))))))
